### ISSUE TITLE
Exception when a newer version is found after checking for updates from the About page

### ISSUE THREAD

**Issue by Timthreetwelve** [Timthreetwelve/HWiNFO-VSB-Viewer#12]
### Is there an existing issue for this?

- [X] I have searched the existing issues (both open and closed).

### What happened or didn't happen?

Checked for new release. New release was found. Clicked 'Yes' to go to releases page. Message box indicated that there was an exception.

### Version

0.4.0

### Windows Version

Windows 11 23H2 build 22631.3447

### Relevant log output

```shell
2024/04/14 16:19:20 DEBUG  Checking GitHub for latest release.
2024/04/14 16:19:21 DEBUG  Latest version is 0.4.0 released on 4/14/2024 9:13:25 PM UTC
2024/04/14 16:19:21 DEBUG  A newer release (0.4.0) has been found.
2024/04/14 16:19:25 ERROR  Error encountered while checking version
System.Exception: Resource not found : MsgText_Opening
   at HWiNFOVSBViewer.Helpers.ResourceHelpers.GetStringResource(String key)
   at HWiNFOVSBViewer.Helpers.GitHubHelpers.CheckRelease()
```

**Comment by Timthreetwelve** [comment]
Fixed in 0.4.1.
